### ISSUE TITLE
Go: Строки / Решение проходит проверку при использовании любого языкового пакета

### ISSUE THREAD

**Issue by ashikov** [hexlet-basics/exercises-go#122]
Перенёс из PR-а #121 и немного дополнил.

Решение проходит проверку при использовании любого языкового пакета (например Arabic, Chinese).
```go
package solution

import (
	"fmt"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// BEGIN (write your solution here)
func Greetings(name string) string {

	name = strings.Trim(name," ")
	name = strings.ToLower(name) 
	name = cases.Title(language.Arabic).String(name)
	return fmt.Sprintf("Привет, %s!", name)
}
```

О cases не рассказывается в теории. Тут просто была пофикшена ошибка линтера, которая возникла вместе с обновлением версии Go. Думаю стоит вернуть strings.Title() и заигнорировать эту ошибку, так как в нашем случае она (вроде бы) не играет роли. Ошибка:

> strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019) go-staticcheck

**Comment by ashikov** [comment]
@forPelevin привет! Может быть ты подскажешь как тут лучше поступить? Игнорить ошибку или же дополнить описание задачи? Плюс мне не совсем понятно, почему решение проходит с любым языковым тегом, то есть текст капитализируется в любом случае. Это я проверял отдельно.

**Comment by forPelevin** [comment]
привет! Давай просто добавим коммент `//nolint` на строке, где вываливается ошибка с депрекацией. Тогда линтер не будет ругаться. 

Почему он срабатывает всегда — хз, это нужно сорсы копать. Мб там есть фоллбек логика, что если не находит язык по тегу, то идет перебором

**Comment by ashikov** [comment]
Спасибо за помощь! Исправил и задеплоил новую версию.
