### ISSUE TITLE
Go: Руны 22/34 : Поправки к решению

### ISSUE THREAD

**Issue by monkrus** [hexlet-basics/exercises-go#124]
Возможный вариант решения кажется более идиоматичным, избегает ненужной конверсии рун.
```
package solution

import (
	"unicode"
)

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] > unicode.MaxASCII {
			return false
		}
	}
	return true
}
```

**Comment by ashikov** [comment]
@forPelevin глянь, пожалуйста

**Comment by forPelevin** [comment]
Привет! 
Я согласен, что это решение быстрее, чем существующее. Единственный вопрос: мы уверены, что не существует такого unicode символа, который будет состоять из нескольких байт < 127?

**Comment by monkrus** [comment]
Да, тогда первоначальное решение остаётся, пожалуй, оптимальным.
