### ISSUE TITLE
В задании на перебор мапы нет перебора мапы

### ISSUE THREAD

**Issue by HelenOne** [hexlet-basics/exercises-go#138]
Тут https://code-basics.com/ru/languages/go/lessons/map-for#comment-6325498439

Вот пример перебора мапы
idToName := map[int64]string{1: "Alex", 2: "Dan", 3: "George"}

// первый аргумент — ключ, второй — значение
for id, name := range idToName {
    fmt.Println("id: ", id, "name: ", name)
}

А в решении перебираются слайсы, а не мапы

**Comment by usernaimandrey** [comment]
Вроде же есть))

В первой части накапливаем результат колличества слов в мапу

```golang
for _, word := range words {
		wordsCount[word]++
		if wordsCount[word] > max {
			max = wordsCount[word]
		}
	}
```

а потом перебираем эту мапу

```golang
for _, word := range words {
		if wordsCount[word] == max {
			mostPopWord = word
			break
		}
	}
```
