### ISSUE TITLE
Описание задания на сортировку слайсов в Golang (18/35)

### ISSUE THREAD

**Issue by MustafinPavel** [hexlet-basics/exercises-go#141]
В описании задания сказано, что "В пакете также присутствует сортировка вставками sort.SliceStable". Но SliceStable имеет под капотом сортировку слиянием, а не вставками.

**Comment by kodsurfer** [comment]
Верно, под "капотом" sort.SliceStable имеет вариацию сортировки слиянием.
[Пруф](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/sort/zsortinterface.go;l=348;drc=635b1244aa7671bcd665613680f527452cac7555) из исходников golang.
