### ISSUE TITLE
Некорректное решение.

### ISSUE THREAD

**Issue by Alorin87** [hexlet-basics/exercises-go#85]
Кодбейсик курс Golang модуль 4.
В задании сказано создать переменную fullName  и вывести её значение.
А в проверочном решении эта переменная не создается и все делается в обход её.
Ясно, что результат тот же, но мы же , по логике, сверяемся с решением учителя :задумчивость:
https://ru.code-basics.com/languages/go/lessons/variables#solution

**Comment by amshkv** [comment]
@forPelevin Влад, посмотри пожалуйста

**Comment by forPelevin** [comment]
Хорошее замечание. Исправлю
