### ISSUE TITLE
20-array-slice-map/25-slice-copy/solution.go - лишнее копирование слайса

### ISSUE THREAD

**Issue by madaraice** [hexlet-basics/exercises-go#98]
Привет! Зачем в данном случае делается копирование слайса через `[:]`? Ведь перед этим идет проверка, что `maxLen `не больше `src` слайса, следовательно, конструкция `[:]` тут лишняя, можно просто вернуть слайс `cp`, разве нет?

https://github.com/hexlet-basics/exercises-go/blob/c8e242f8fe15f2e5cf30cc2942a33e2e0a514102/modules/20-array-slice-map/25-slice-copy/solution.go#L20

**Comment by forPelevin** [comment]
привет! Отличное замечание. В данном случае действительно не нужно ограничивать по maxLen, потому что выше есть проверка
https://github.com/hexlet-basics/exercises-go/pull/104/files
